<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?> </div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?= _calificaciones("Aprovar calificaciones y comentarios") ?></h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
                <form name="buscarGrid" action="" method="get" id="paginar">                
                    <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                </form>
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin calificaciones">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);

    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'coments',
        redirectOnSelectRow:false,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '',
        pathData : window.location.pathname,
        error : "<?=_calificaciones("No hay calificaciones y/o comentarios registrados")?>",
        deleteFunction : "Calificaciones_AprovarCalificacion",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Comentario')?>', name: 'comentario', hidden:true, width: 50 },
            { label: '<?=_('Fecha')?>', name: 'createdAt', hidden:isGridMobile, width: 200,
                
                searchoptions: {
                    dataInit: function (element) {
                        $(element).datepicker({
                            id: 'orderDate_datePicker',
                            dateFormat:"yy-mm-dd",
                            maxDate: "+0D",
                            showOn: 'focus'
                        });
                    },
                    sopt: ["ge","le","eq"]
                }
            },
            { label: '<?=_('Item')?>', name: 'item', width: 250 },
            { label: '<?=_('Nombre')?>', name: 'nombre', hidden:isGridMobile, width: 250, search:false },
            { label: '<?=_('Email')?>', name: 'email', hidden:isGridMobile, width: 250, search:false },
            { label: '<?=_('Titulo')?>', name: 'titulo', width: 250 },
            { label: '<?=_('Calificacion')?>', name: 'calificacion', hidden:isGridMobile, width: 250 },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
            }
        ],
        subGrid: true,
        subGridRowExpanded: showChildGrid
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#activar"><span class="icon icon-valido"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#desactivar"><span class="icon '+icon_delete+'"> </span></a>';
 
    return boton1 + boton2;                       
}

function showChildGrid(parentRowID, parentRowKey) {
        var childGridID = parentRowID + "_table";
        var childGridPagerID = parentRowID + "_pager";
        if($(window).width() <= 767) {
      
            var fecha  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_createdAt"]').text();
            var nombre  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_nombre"]').text();
            var email  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_email"]').text();
            var calificacion  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_calificacion"]').html();
            
            $('#' + parentRowID).append('<p>Fecha: '+fecha+'</p>');
            $('#' + parentRowID).append('<p>Nombre: '+nombre+'</p>');
            $('#' + parentRowID).append('<p>URL: '+email+'</p>');
            $('#' + parentRowID).append('<p>Idioma: '+calificacion+'</p>');
            
        }
        
        var comentario  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_comentario"]').text();
        $('#' + parentRowID).append('<p>'+comentario+'</p>');


    }
</script>
